brain/brain/urls.py
from django.urls import path,include
from django.contrib import admin
from django.contrib.auth import views as authentication_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('home.urls')),

]

brain/home/urls.py
from django.urls import path,include
from django.contrib import admin
from . import views
from django.contrib.auth import views as authentication_views


app_name = 'home'

urlpatterns = [

    path('',views.index,name='index'),
    path('signup/',views.signup,name='signup'),
    path('otp/',views.otp,name='otp'),
    path('login/',authentication_views.LoginView.as_view(template_name='home/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name='home/logout.html'),name='logout'),



]

brain/home/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from passwords.fields import PasswordField
# Create your models here.

brain/home/forms.py
from django import forms
from passwords.fields import PasswordField
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from phonenumber_field.formfields import PhoneNumberField
from passwords.fields import PasswordField

from django.contrib.auth.models import User

class loginform(UserCreationForm):
    Email = forms.EmailField()
    Phone = PhoneNumberField()
    class Meta:

        model = User
        fields = ['username', 'Email', 'Phone', 'password1', 'password2']

brain/home/views.py
from django.shortcuts import render,redirect
from .forms import loginform
from django.contrib import messages
from twilio.rest import Client
import random
from django.core.mail import EmailMessage
from django.contrib.auth.forms import User
from django.contrib.auth.decorators import login_required

from django.core.exceptions import ValidationError

# Create your views here.

def index(request):
    return render(request,'home/index.html')

def signup(request):
    form = loginform(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            mobile = form.cleaned_data.get('Phone')
            username = form.cleaned_data.get('username')
            email1 = form.cleaned_data.get('Email')
            otp = random.randint(0000,9999)
            request.session['OTP_1']=otp
            account = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' #your account of twilio
            token = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' #token of twilio
            client = Client(account, token)
            client.messages.create(from_='+16415696832', to="" + str(mobile),body='Welcome ' + str(username) + ' to our Aliensworld verifcation code is ' + str(otp))
            email = EmailMessage('Account activation',str(otp),to=[email1])
            email.send()
            return redirect('home:otp')
    return render(request,'home/signup.html',{'form':form})


def otp(request):
    if request.method == 'POST':
        otp1 = request.session['OTP_1']
        otp = request.POST.get('otp')
        if int(otp1)==int(otp):
            messages.success(request, "Welcome to AliensWorld")
            return render(request,'home/index.html')
        else:
            messages.info(request, 'sorry you typed wrong OTP')
    return render(request,'home/otpverification.html')

brain/home/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
    {% if user.is_authenticated %}
    <a href="{% url 'home:logout' %}">Logout</a>
    {% else %}
    <a href="{% url 'home:login' %}">Login</a>
    {% endif %}

<h2>Welcome to home page {{user}}</h2>
<h3>verification starting</h3>


</body>
</html>

brain/home/templates/home/login.html
{% csrf_token %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login Page</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    <table>{{form}}</table>
    <button type="submit">Login</button>
</form>
{% if messages %}
{% for message in messages %}
    <h3>{{message}}</h3>
{% endfor %}
{% endif %}
</body>
</html>

brain/home/templates/home/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Logout</title>
</head>
<body>
<h2>You are logged out </h2>
</body>
</html>

brain/home/templates/home/otpverification.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>OTP Verification</title>
</head>
<body>
{% if messages %}
{% for message in messages %}
    {{message}}
{% endfor %}
{% endif %}
<form method="post">
    {% csrf_token %}
<h1>OTP Verification</h1>
    <input type="text" name="otp"placeholder="Enter OTP">
    <input type="submit" value="submit">
</form>


</body>
</html>

brain/home/templates/home/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Signup</title>
</head>
<body>

{% if messages %}
{% for message in messages%}

    {{message}}

{% endfor %}
{% endif %}

<h1>Signup</h1>
<form method="post">
    {% csrf_token %}
    <table>
       {{form}}

    </table>
    <input value="submit"type="submit">
</form>
</body>
</html>